### ISSUE TITLE
Undefined expat symbols

### ISSUE THREAD

**Issue by thezbyg** [thezbyg/gpick#112]
Original [issue 112](https://code.google.com/p/gpick/issues/detail?id=112) created by thezbyg on 2013-12-19T05:48:52.000Z:

<b>What steps will reproduce the problem?</b>
1. Remove &quot;'-Wl,-as-needed'&quot; from SConscript (see bug #&nbsp;111) 
2. scons &amp;&amp; make

<b>What is the expected output? What do you see instead?</b>
Expected successful compile but got:

Undefined symbols:
  &quot;_XML_ParseBuffer&quot;, referenced from:
      dynv_xml_deserialize(dynvSystem_, std::basic_istream&lt;char, std::char_traits&lt;char&gt; &gt;&amp;)in DynvXml.o
  &quot;_XML_SetCharacterDataHandler&quot;, referenced from:
      dynv_xml_deserialize(dynvSystem_, std::basic_istream&lt;char, std::char_traits&lt;char&gt; &gt;&amp;)in DynvXml.o
  &quot;_XML_SetUserData&quot;, referenced from:
      dynv_xml_deserialize(dynvSystem_, std::basic_istream&lt;char, std::char_traits&lt;char&gt; &gt;&amp;)in DynvXml.o
  &quot;_XML_ParserFree&quot;, referenced from:
      dynv_xml_deserialize(dynvSystem_, std::basic_istream&lt;char, std::char_traits&lt;char&gt; &gt;&amp;)in DynvXml.o
  &quot;_XML_SetElementHandler&quot;, referenced from:
      dynv_xml_deserialize(dynvSystem_, std::basic_istream&lt;char, std::char_traits&lt;char&gt; &gt;&amp;)in DynvXml.o
  &quot;_XML_GetBuffer&quot;, referenced from:
      dynv_xml_deserialize(dynvSystem_, std::basic_istream&lt;char, std::char_traits&lt;char&gt; &gt;&amp;)in DynvXml.o
  &quot;_XML_ParserCreate&quot;, referenced from:
      dynv_xml_deserialize(dynvSystem_, std::basic_istream&lt;char, std::char_traits&lt;char&gt; &gt;&amp;)in DynvXml.o
ld: symbol(s) not found
collect2: ld returned 1 exit status
scons: *_\* [build/source/gpick] Error 1
scons: building terminated because of errors.

<b>What version of the product are you using? On what operating system?</b>
gpick 0.2.5, Mac OS X 10.5.8, Xcode 3.1.4, gcc version 4.0.1 (Apple Inc. build 5493)

<b>Please provide any additional information below.</b>
Seems like &quot;-lexpat&quot; is missing somewhere, but scons scripts are a mystery to me so I don't know where best to add it.

**Comment by ryandesign** [comment]
Just as a reminder, this problem remains with the latest gpick code in the repo today, on macOS High Sierra.
