### ISSUE TITLE
Please create an AppData file for Gpick

### ISSUE THREAD

**Issue by thezbyg** [thezbyg/gpick#117]
Original [issue 117](https://code.google.com/p/gpick/issues/detail?id=117) created by thezbyg on 2014-05-28T10:30:28.000Z:

Please consider writing and installing an AppData file with the application description and some screenshots, else Gpick looks really bad in the GNOME and KDE Software Centers. We'd love to showcase more applications, but without the extra data file we can't. See http://people.freedesktop.org/~hughsient/appdata/ for details; thanks!

Richard

**Comment by luyatshimbalanga** [comment]
Hello thezbyg,
Do you know when you will add the appdata file for gpick as it comment already made it for you?
Thanks
