### ISSUE TITLE
Migrate to github or similar site

### ISSUE THREAD

**Issue by thezbyg** [thezbyg/gpick#122]
Original [issue 122](https://code.google.com/p/gpick/issues/detail?id=122) created by thezbyg on 2015-03-13T04:34:36.000Z:

Google Code is shutting down (http://google-opensource.blogspot.com/2015/03/farewell-to-google-code.html).

They have added a button to Google Code &quot;Export to Github&quot;. This will automatically convert Mercurial (in gpick's case) repositories to Git and transfer the repository across. It will also transfer all issues that are not labelled Restrict-View-\* to Github, as well as all wiki content (automatically converting it to Github's native format, MarkDown)

We have some time to get this done (Site becomes fully read-only in August 2015, final shutdown is in January 2016), so, while it's perfectly possible for anyone to do the migration in theory,  I thought we should probably take the opportunity to sort out any potential details.

If nobody replies here (or exports the project) by the end of March, then I will be hitting the Export button at the end of March.

**Comment by Weej1** [comment]
Glad to see you hit it before I could! Are there any updated PPAs for gpick?

**Comment by thezbyg** [comment]
I will update my own PPA at https://launchpad.net/~thezbyg/+archive/ubuntu/ppa
Currently only amd64 build succeeded, but I have already fixed the issue and just need to re-upload.

**Comment by 0ion9** [comment]
That's weird, I created that issue. Looking at other issues, it seems like all issues are treated as if they were submitted by the user who hit export. Oh well, doesn't matter that much.

**Comment by 0ion9** [comment]
I just checked the windows download link, and it's broken (download link points to code.google.com, which redirects back to here.). Not sure what the correct thing to do is.

**Comment by dogancelik** [comment]
I checked [Releases page](https://github.com/thezbyg/gpick/releases) and It only has source code. Could you please add binaries?

**Comment by Ytrog** [comment]
This seems to be done 👀
