### ISSUE TITLE
Import from text file with RGB codes

### ISSUE THREAD

**Issue by PanderMusubi** [thezbyg/gpick#128]
Please, offer functionality to import RGB codes from text file. Each on one line, the hash (#) at the beginning is optional. All whitespace (leading and trailing spaces and tabs and empty lines) should be ignored.

**Comment by thezbyg** [comment]
Added "File->Import Text File..." menu item and dialog with various options.
This allows importing colors from all kinds of text files.

**Comment by PanderMusubi** [comment]
Thanks.

As sort of related question, would you ship also certain default palettes with gpick? For example the color palettes of Google's Material Design.
