### ISSUE TITLE
Show nearest color from palette

### ISSUE THREAD

**Issue by PanderMusubi** [thezbyg/gpick#129]
When right clikcing on one of the six picked colors, offer a menu item called "Show nearest color from palette"

Support the palette contains #ffff00 and #ff0000 and the picked color is #ffee00, then #ffff00 (with its names) would be shown. This would be calculated with root mean square error and the most minimal distance is the nearest color.

Alternatively, this could list the three nearest colors in a sub menu, as the "Copy to clipboard" has a submenu. The color chosen would also be copied to clipboard.

**Comment by thezbyg** [comment]
Hi,
does this look like what you are asking for?
![nearest_color_example](https://cloud.githubusercontent.com/assets/129256/14119825/b084fa2c-f5f8-11e5-9586-b49e7f727e62.png)

**Comment by PanderMusubi** [comment]
Yes, exactly like that. And choosing it copies the RGB value in the copy paste buffer?

**Comment by thezbyg** [comment]
Yes, color value gets put to the copy/paste buffer by using the first item from the Converters dialog with Copy checkbox enabled. By default the first Converter is "Web: hex code", which outputs colors in full hexadecimal format (#a1b2c3).

**Comment by PanderMusubi** [comment]
Thanks
