### ISSUE TITLE
Failure to build gpick with scons

### ISSUE THREAD

**Issue by luyatshimbalanga** [thezbyg/gpick#134]
While applying the update from the latest commit, I encountered an issue
https://kojipkgs.fedoraproject.org//work/tasks/6861/14456861/build.log

Would you mind to investigate the problem?

**Comment by thezbyg** [comment]
Looks like `abs` function for float type has been added to standard C++ library, and it conflicts with custom abs implementation. Please update to 569ee0f165b689825efd0cb7da1695beb7f8aa9b and try building again.

**Comment by luyatshimbalanga** [comment]
Applying the update made the build succeeding as seen below
[build.log.txt](https://github.com/thezbyg/gpick/files/313266/build.log.txt)
 Thanks for resolving the issue. I am closing this bug.
