### ISSUE TITLE
Bug: 0.2.5 save/export doesn't format (Fedora 25 internal install)

### ISSUE THREAD

**Issue by CitySelby** [thezbyg/gpick#140]
When I try to save a palette the program doesn't seem to attribute any format to it; by that I mean there's no .ext - it becomes listed as 'binary (application/octet-stream)'- and I have no way of opening the file with any relevant program, including gpick (which doesn't even show up in the related applications window), GIMP, or inkscape. Attempting to export does the same except for .txt , .css , and .html . The only way to keep a palette aside from those three is to have the program reload it upon starting.

Thank you.

**Comment by thezbyg** [comment]
Currently Gpick does not modify entered file name, so if no extension is entered when saving or exporting, then extension-less file is created.
I have added save and export file name checks to append extensions if no extension is entered, so missing file extensions should be fixed after commit 1d6da2d981555705c75976bd1291e1594e00e4be.

I will also add some content based file type recognition tomorrow, to allow opening these extension-less files.

**Comment by thezbyg** [comment]
Content based file format detection have been added (commit fa2d3e43f37e297e345f5b0d1468818e8e67fea1). Gpick should now successfully open *.gpa and *.gpl files even with missing extensions.
