### ISSUE TITLE
gpick tray icon (wishlist)

### ISSUE THREAD

**Issue by newhoa** [thezbyg/gpick#145]
Is there any way that, in addition to the gpick.svg/png application icon, gpick could also use a gpick-tray.svg (or png) icon as the tray specific icon? Also with the move to Gtk3, many panels have started requiring the use of symbolic icons, so a gpick-tray-symbolic might also be helpful as far as theming.

I was working on an icon theme and a gpick icon has been requested quite a few times! Many icon themes (including mine for the most part) use monochrome or less detailed icons for the tray as those are lot easier to see quickly. Many of the applications that I've themed so far that use the tray have a standard app icon and then a tray-specific icon (and then also now a tray-specific symbolic icon). With gpick I either have to do a simple or blended mono icon for the tray and then have the app icon look off, or do a nice app icon and have the tray icon look radically different than everything else in the tray.

Anyway, thanks so much for this great program, I've used it for a very long time and really enjoy it!

**Comment by thezbyg** [comment]
Main and status icons are now separate (commit 17747bb03740c5b5388d5762e7179ce858ff93af).
So in new versions it will be possible to have different icon for tray icon. Tray icon will be named _gpick-tray_.
I am not familiar with symbolic icons, and, after some searching and reading, I am not yet sure what has to be done from application side to support them.

**Comment by fbruetting** [comment]
Tray widgets are deprecated in Gnome, see the Gnome wiki for details.

**Comment by newhoa** [comment]
Thanks very much for this! Symbolic icons are specific to Gtk3. I'm not sure if the app itself has to use Gtk3 to support them or not (other Gtk3 apps, like panels, seem to call for them). Most of the icons I've seen use symbolic icons, the apps themselves have been Gtk3 apps, so that might be the case.

Anyway, just for fun [here's the icon I made](https://imgur.com/a/zMIxv)! (the circular one). Thanks again for the modification, I really appreciate it!
