### ISSUE TITLE
appdata directory renamed metainfo

### ISSUE THREAD

**Issue by luyatshimbalanga** [thezbyg/gpick#146]
[Appstream guideline ](https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps) recently rename `appdata` directory to `metainfo`. The fix is very trivial as this example illustrated: `/usr/share/metainfo/gpick.appdata.xml`. Affected files are SConscript.

**Comment by thezbyg** [comment]
Fixed in commit 4d968eaeaa2c6c256c083d8128542df3c7a25b1d.
Thanks.
