### ISSUE TITLE
Target "lua" links to itself

### ISSUE THREAD

**Issue by ryandesign** [thezbyg/gpick#156]
I'm trying to use gpick's new cmake build system. It fails for me on macOS High Sierra with:

```
CMake Error at CMakeLists.txt:100 (add_library):
  Target "lua" links to itself.
```

**Comment by thezbyg** [comment]
Should be fixed by 632faeb540caf340425adfd0d29aa6131a5e5777. If problem persists, then please run `cmake` command with `-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON` option to build verbose makefile, and, after running `make`, provide either whole output or last lines before failure.

**Comment by ryandesign** [comment]
It seems to get through the build, but fail at linking, with missing lua symbols, because `-llua` isn't in the link line.

https://gist.github.com/ryandesign/092ac49df5a3dafe073dcd89bfb8eefe

**Comment by thezbyg** [comment]
Please provide lines from CMakeCache.txt file starting with the following strings:
`pkgcfg_lib_Lua_lua`
`Lua_LIBRARIES`
`Lua_VERSION`

And also results of running the following commands:
`pkg-config --libs lua5.3`
`pkg-config --libs lua5`
`pkg-config --libs lua`
`pkg-config --libs lua5.2`

**Comment by thezbyg** [comment]
It turns out that in CMake both system and internally declared libraries live in the same name space, and your Lua library is called `lua` which was the name of the internal Lua utility library. This should now be fixed.
