### ISSUE TITLE
[Feature Request] Write HEX code to create color

### ISSUE THREAD

**Issue by adriencarbonaro** [thezbyg/gpick#170]
There is the possibility of writing RGB code to create color but it don't work with a HEX code.
It would be a good feature.

**Comment by thezbyg** [comment]
New **Add color** dialog has been added:
![add-color](https://user-images.githubusercontent.com/129256/66075112-8bb61600-e563-11e9-9238-b37710663b3b.png)

It supports all formats enabled in **Converters** dialog **Paste / Edit** column:
![add-color-formats](https://user-images.githubusercontent.com/129256/66074638-4fce8100-e562-11e9-9cab-f185654bf5b3.png)

**Comment by adriencarbonaro** [comment]
Great! Thanks!
