### ISSUE TITLE
Segfault when moving two or more items in the palette list to the end of the list

### ISSUE THREAD

**Issue by Diomendius** [thezbyg/gpick#171]
**Version:** Gpick 0.2.6rc1

When selecting two or more list items and dragging them to the end of the list, the program crashes when the mouse is released and gives this output:

```
(gpick:32581): Gtk-CRITICAL **: 18:24:50.458: gtk_list_store_get_value: assertion 'VALID_ITER (iter, list_store)' failed

(gpick:32581): GLib-GObject-WARNING **: 18:24:50.458: ../glib/gobject/gtype.c:4265: type id '0' is invalid

(gpick:32581): GLib-GObject-WARNING **: 18:24:50.458: can't peek value table for type '<invalid>' which is not currently referenced
Segmentation fault (core dumped)
```

This might be related to #70, but evidently the fix for that issue does not affect this one.

**Comment by thezbyg** [comment]
This issue should be fixed now. Please try reproducing and report your results.

**Comment by Diomendius** [comment]
Just built and tested master and everything works as expected now. Looks like you fixed it.
