### ISSUE TITLE
Shortcuts don't work in non-Latin keyboard layout

### ISSUE THREAD

**Issue by prokoudine** [thezbyg/gpick#176]
When Russian keyboard layout is active, shortcuts like Ctrl+C / Ctrl+V / Ctrl+P don't work. This is strange as GTK+ apps usually don't have this issue on Linux.

**Comment by thezbyg** [comment]
Should be fixed now. Keyboard event handling code wrongly assumed that GTK event key values were keyboard layout independent.

**Comment by prokoudine** [comment]
Yeah, seems fixed now!
