### ISSUE TITLE
List of colors in Generate Colors doesn't auto-expand

### ISSUE THREAD

**Issue by prokoudine** [thezbyg/gpick#179]
In the GTK2 version, the _Generate Colors_ dialog used to auto-expand the list of colors to be generated. Now the widget has a small fixed height, and one has to use the tiny scrollbar to navigate. Using a HiDPI display here, if that's of any importance :)

![Снимок экрана от 2020-04-17 00-34-36](https://user-images.githubusercontent.com/57467/79509059-77d78a80-8043-11ea-9e22-9aaed0d25096.png)

**Comment by thezbyg** [comment]
Should be fixed.

**Comment by prokoudine** [comment]
It is, thank you!
