### ISSUE TITLE
How do you mix colors?

### ISSUE THREAD

**Issue by obtusedev** [thezbyg/gpick#206]
Is there documentation for how to mix colors? I can't figure it out for the life of me.

**Comment by thezbyg** [comment]
Hi,
these wiki pages should help: [wiki/MixColors](../wiki/MixColors), [wiki/ColorMixer](../wiki/ColorMixer), [wiki/BlendColors](../wiki/BlendColors).
If you need some other type of color mixing the please be more specific and describe what you are trying to achieve.

**Comment by obtusedev** [comment]
Thanks! Couldn't find the information on the gpick.org/help
